<?php
/*
 * (c) 2026: 975L <contact@975l.com>
 * (c) 2026: Laurent Marquet <laurent.marquet@laposte.net>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */
namespace c975L\ConfigBundle\Management;

use Symfony\Bundle\SecurityBundle\Security;
use Symfony\Contracts\Translation\TranslatorInterface;

// Merges the guided projects contributed by every GuidedProjectProvider, sorted by "order" - a deliberate sequence (create a page, then add a block to it, then put it in a menu), not the alphabetical merge MenuBuilder/AlertBuilder use, same as EssentialActionBuilder. Labels and descriptions are resolved here rather than left to the template: the panel walking a project through is JavaScript (see assets/js/guided-project.js), fed by GuidedProjectController's JSON, and there is no translator on that side
class GuidedProjectBuilder
{
    public function __construct(
        private readonly iterable $guidedProjectProviders,
        private readonly Security $security,
        private readonly TranslatorInterface $translator,
    ) {
    }

    // Every project, across every provider, sorted by "order" - one needing a role the current user lacks is dropped, the screens it walks through being out of their reach anyway (same treatment as a sidebar link, see MenuProviderInterface::getLinks())
    public function getProjects(): array
    {
        $projects = ProviderMerger::merge($this->guidedProjectProviders, fn (GuidedProjectProviderInterface $provider) => $provider->getGuidedProjects());

        $projects = array_filter($projects, fn (array $project) => !isset($project['role']) || $this->security->isGranted($project['role']));
        usort($projects, fn (array $a, array $b) => $a['order'] <=> $b['order']);

        return array_map(fn (array $project) => $this->buildProject($project), $projects);
    }

    // One project by its slug, or null when no provider declares it anymore (a bundle uninstalled since the browser stored it) or when the current user lacks its role - a slug being theirs to forge, that second check is the only thing standing between them and another role's parcours
    public function getProject(string $slug): ?array
    {
        foreach ($this->getProjects() as $project) {
            if ($slug === $project['slug']) {
                return $project;
            }
        }

        return null;
    }

    private function buildProject(array $project): array
    {
        $domain = $project['translation_domain'];

        return [
            'slug' => $project['slug'],
            'label' => $this->translator->trans($project['label'], [], $domain),
            'description' => empty($project['description']) ? '' : $this->translator->trans($project['description'], [], $domain),
            'steps' => array_map(fn (array $step) => $this->buildStep($step, $domain), $project['steps']),
        ];
    }

    // "url" and "highlight" go through untranslated - the first is generated by the contributing bundle, the second is a CSS selector
    private function buildStep(array $step, string $domain): array
    {
        return [
            'label' => $this->translator->trans($step['label'], [], $domain),
            'description' => empty($step['description']) ? '' : $this->translator->trans($step['description'], [], $domain),
            'url' => $step['url'] ?? null,
            'highlight' => $step['highlight'] ?? null,
        ];
    }
}
