// ESLint 9 flat configuration, read by Codacy and by the local Codacy CLI
// Only correctness rules are enabled, formatting is left to the developer
export default [
    {
        ignores: ["public/**", "vendor/**", "**/*.min.js"],
    },
    {
        files: ["**/*.js", "**/*.mjs"],
        languageOptions: {
            ecmaVersion: 2024,
            sourceType: "module",

            // Browser globals used across the c975L bundles, plus the third-party ones loaded by AssetMapper
            globals: {
                clearInterval: "readonly",
                clearTimeout: "readonly",
                confetti: "readonly",
                console: "readonly",
                CSS: "readonly",
                CustomEvent: "readonly",
                DataTransfer: "readonly",
                document: "readonly",
                Event: "readonly",
                fetch: "readonly",
                File: "readonly",
                FileReader: "readonly",
                history: "readonly",
                Image: "readonly",
                IntersectionObserver: "readonly",
                localStorage: "readonly",
                navigator: "readonly",
                Node: "readonly",
                requestAnimationFrame: "readonly",
                screen: "readonly",
                setInterval: "readonly",
                setTimeout: "readonly",
                Trix: "readonly",
                URL: "readonly",
                URLSearchParams: "readonly",
                window: "readonly",
            },
        },
        rules: {
            "constructor-super": ["error"],
            "for-direction": ["error"],
            "getter-return": ["error"],
            "no-async-promise-executor": ["error"],
            "no-case-declarations": ["error"],
            "no-class-assign": ["error"],
            "no-compare-neg-zero": ["error"],
            "no-cond-assign": ["error", "except-parens"],
            "no-const-assign": ["error"],
            "no-constant-condition": ["error"],
            "no-control-regex": ["error"],
            "no-debugger": ["error"],
            "no-delete-var": ["error"],
            "no-dupe-args": ["error"],
            "no-dupe-class-members": ["error"],
            "no-dupe-else-if": ["error"],
            "no-dupe-keys": ["error"],
            "no-duplicate-case": ["error"],
            "no-empty": ["error"],
            "no-empty-character-class": ["error"],
            "no-empty-pattern": ["error"],
            "no-ex-assign": ["error"],
            "no-fallthrough": ["error"],
            "no-func-assign": ["error"],
            "no-global-assign": ["error"],
            "no-import-assign": ["error"],
            "no-inner-declarations": ["error"],
            "no-invalid-regexp": ["error"],
            "no-loss-of-precision": ["error"],
            "no-misleading-character-class": ["error"],
            "no-obj-calls": ["error"],
            "no-octal": ["error"],
            "no-prototype-builtins": ["error"],
            "no-redeclare": ["error"],
            "no-regex-spaces": ["error"],
            "no-self-assign": ["error"],
            "no-setter-return": ["error"],
            "no-shadow-restricted-names": ["error"],
            "no-sparse-arrays": ["error"],
            "no-this-before-super": ["error"],
            "no-undef": ["error"],
            "no-unreachable": ["error"],
            "no-unsafe-finally": ["error"],
            "no-unsafe-negation": ["error"],
            "no-unsafe-optional-chaining": ["error"],
            "no-unused-labels": ["error"],
            "no-unused-vars": ["error"],
            "no-useless-backreference": ["error"],
            "no-useless-catch": ["error"],
            "no-useless-escape": ["error"],
            "no-with": ["error"],
            "require-yield": ["error"],
            "use-isnan": ["error"],
            "valid-typeof": ["error"],
        },
    },
];
