services:
    _defaults:
        autowire: true
        autoconfigure: true

    c975L\ConfigBundle\Command\:
        resource: '../src./Command/*'

    c975L\ConfigBundle\Form\:
        resource: '../src/Form/*'

    c975L\ConfigBundle\Service\:
        resource: '../src/Service/*'

    c975L\ConfigBundle\Twig\:
        resource: '../src/Twig/*'