services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    c975L\ConfigBundle\:
        resource: '../src/'
        exclude: '../src/{DependencyInjection,Entity}'

    c975L\ConfigBundle\Controller\Management\DashboardController:
        arguments:
            $menuProviders: !tagged_iterator c975l.management_menu_provider
        tags: ['controller.service_arguments']

